# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170512_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='www.baidu.com', verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
